# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      WAYPOINT_SERVER_ADDR: ${{ secrets.WAYPOINT_SERVER_ADDR }}
      WAYPOINT_SERVER_TLS: 1
      WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - uses: hashicorp/action-waypoint
      name: Setup
      with:
        version: '0.0.1-beta1'
        WAYPOINT_GITHUB_TOKEN: ${{ secrets.WAYPOINT_GITHUB_TOKEN }}
        waypoint_server_address: ${{ secrets.WAYPOINT_SERVER_ADDR }} 
        waypoint_server_ui: ${{ secrets.WAYPOINT_SERVER_ADDR_UI }}'
        waypoint_server_token: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
        workspace: default
    - uses: hashicorp/action-waypoint
      name: Build
      with:
        operation: build
        version: '0.0.1-beta1'
        WAYPOINT_GITHUB_TOKEN: ${{ secrets.WAYPOINT_GITHUB_TOKEN }}
        workspace: default
    - uses: hashicorp/action-waypoint
      name: Deploy
      with:
        operation: deploy
        version: '0.0.1-beta1'
        WAYPOINT_GITHUB_TOKEN: ${{ secrets.WAYPOINT_GITHUB_TOKEN }}
        workspace: default
    - uses: hashicorp/action-waypoint
      name: Release
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        operation: release
        version: '0.0.1-beta1'
        WAYPOINT_GITHUB_TOKEN: ${{ secrets.WAYPOINT_GITHUB_TOKEN }}
        workspace: default
    - name: Waypoint-Initailize
      run: waypoint init
    - name: Waypoint-Build  
      run: waypoint build
